version: '3.4'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  helloworldapi:
    image: ${DOCKER_REGISTRY-}helloworldapi
    build:
      context: .
      dockerfile: HelloWorldAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data: